"""Phase 2: each participant gets two turns of critique."""

CRITIQUE_PROMPT = (
    "Phase 2 of the discussion: Critique (round {round_number} of {round_total}).\n\n"
    "The group has been asked the following question:\n\n"
    "<<<\n{question}\n>>>\n\n"
    "Here is a Credential Summary the orchestrator built about each "
    "participant. Use it the way a thoughtful person in a real meeting would: "
    "weight statements appropriately, but don't let it shut down good ideas "
    "from less-credentialed voices.\n\n"
    "Credential Summary:\n{credential_summary}\n\n"
    "Conversation so far:\n{transcript}\n\n"
    "It is now your turn.\n\n"
    "{pending_block}"
    "In a focused 5-10 sentence response:\n"
    "  1. FIRST, if any open threads were directed at you above, address "
    "them - by name and clearly. A natural follow-up question back to that "
    "participant is fine.\n"
    "  2. THEN offer constructive criticism of one or two other "
    "participants' opinions, naming them directly and citing specific "
    "points (not vibes).\n"
    "  3. Ask any follow-up questions of specific participants where you "
    "want a clearer answer.\n"
    "  4. Revise your own opinion if (and only if) the discussion has "
    "given you reason to. If you've revised, say so explicitly.\n\n"
    "Stay in character. Do not try to wrap up the discussion - we are not "
    "near the end yet."
)
